### ISSUE TITLE
Redesign of relative expressions

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSMOSES#12]
Basis for discussion of "Redesign of relative expressions".

Known Problems with the status quo:
1. Normalization (`relExp`➡️ `relExp_norm`). Is currently done in PK-Sim and not part of generated model. Problems here:
  a. If values must be changed manually (in MoBi, via R-Toolbox, etc.), normalization is not done anymore
  b. Writing parameter values back from a PI is complicated and error prone
  c. relExp-parameters are still present in the model, but not used. Very confusing for users
  d. Extending models in MoBi with new organs (containing relative expressions) is complicated
2. Localization in XXX. Currently only part of PK-Sim logic. Should we try to bring it somehow to MoBi  (especially if we are going to add proteins in MoBi as well)?

**Comment by msevestre** [comment]
This is a very complicated problem and I have no real idea how to solve this

Maybe usage of SumFormula could help for normalization? 

1.a Changing value is always done to the normalized value so I don't ee why there is an issue.
1.b Same here. why is this error prone? 
1.c agreed
1.d agreed

2. This is even more complicated.

**Comment by Yuri05** [comment]
>Maybe usage of SumFormula could help for normalization?

Yep, don't think it's possible without sum formulas

a+b) Because in MoBi we have non-normalized values in model (which are not used at all once normalization is done) and normalized values. Very confusing. And the opposite of what we have in PK-Sim (where **non-normalized** values are edited)

> 2. This is even more complicated.

yep. It is for sure possible to define localization properties as part of the model; the formulas would become pretty ugly (similiar to the current pKa-pH-Dependency of intestinal solubility and partition coefficients)

**Comment by msevestre** [comment]
sure. But assuming we would only have normalized value in pkml. We would be ok right?

**Comment by msevestre** [comment]
(I mean for a + b).

**Comment by StephanSchaller** [comment]
But is 1) not also an issue due to localization in 2)?
Normalization is required as local values are derived from overall tissue expression, right?
Or what is the normalization for?

**Comment by Yuri05** [comment]
>Or what is the normalization for?

https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-expression-data#reference-concentration 😉

**Comment by StephanSchaller** [comment]
> https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-expression-data#reference-concentration 😉

Maybe I am blind, but there is nothing on "normalization"...?
Or do you mean the relative Expression is always normalized to the highest expressing organ?...

I would vote for removing (automated re-) normalization within the software.
We can normalize the database, but if you then define expression as 200%, why not?... makes life much easier...

**Comment by Yuri05** [comment]
>Or do you mean the relative Expression is always normalized to the highest expressing organ?

Exactly.

>We can normalize the database, but if you then define expression as 200%, why not?... makes life much easier...

Well, worth to discuss it.

**Comment by msevestre** [comment]
>I would vote for removing (automated re-) normalization within the software.

Why would we do this?

>We can normalize the database, but if you then define expression as 200%, why not?... makes life much easier...

This can be achieved by setting your norm value to 2 as the max will be 1 per construction. This is already available.

**Comment by StephanSchaller** [comment]
> Why would we do this?

it leads to very strange / unexpected behaviour when trying to fit expression levels via the PI.

> This can be achieved by setting your norm value to 2 as the max will be 1 per construction. This is already available.

But what happens then? Let's say your max value was "1" for two organs when loading the expression values (the corresponding normalized value for both organs is 100%).
You then change the rel. expression for one organ to two --> the normalized expressions for all organs except this one get reduced by 50%, and as I understood it, so will the effective resulting concentrations in all these organs.
However, what the user likely expects is, that the effective concentration for only this organ for which you increased the relative expression to two gets doubled.

For the PI, this means...if you fit a relative expression (which already is close to 1), the PI will automatically downscale the expression in all other organs once the fitted value goes above 1.
This causes problems for the PI and also is unexpected behaviour (in my opinion).

**Comment by msevestre** [comment]
>However, what the user likely expects is, that the effective concentration for only this organ for which you increased the relative expression to two gets doubled.

I am not sure about this. In PK-Sim, this is quite clear what's going on as you see the percentage changing. 

In Mobi, changing the rel exp values has absolutely no meaning whatsoever (which is what is confusing in the first place). 

>or the PI, this means...if you fit a relative expression (which already is close to 1)

Unless you change the default behavior of the parameters (e.g. manipulate CanBeVaried to which case you are responsible for your own mess), you can only optimize the normalizes values. e.g what you are describing is not possible (see picture)

# Mobi
![image](https://user-images.githubusercontent.com/1041237/73316099-fd475d80-41ff-11ea-8935-f0f306b2b240.png)

# PK-Sim
![image](https://user-images.githubusercontent.com/1041237/73316354-9f674580-4200-11ea-90e5-15338485578a.png)

So I am not quite sure what the problem is. The actual relative expression parameter are changed that's true, but this has no bearing on the normalized parameter (which are the only parameter used in the simulation)

**Comment by PavelBal** [comment]
I vote for removing the "normalization" at all, it was/is always confusing, not only in MoBi, but also in PK-Sim.

Example in PK-Sim - a protein with reference concetration of 1 µmol/L, relative expression = 1 in the kidney, and 0.5 in the liver. Now, during model development, I realize that I want to remove the protein from the kidney - the natural thing to do is to set the relative expression there to 0. But what happens at the same time (and really not obvious to the user), is that the concentration of the protein in the liver is increased from 0.5 to 1!

**Comment by Yuri05** [comment]
>I vote for removing the "normalization" at all, it was/is always confusing, not only in MoBi, but also in PK-Sim.

I agree. What we could do:
1. Remove normalized relExp, keep only relExp
2. relExpOut=f(relExp) (anstatt wie jetzt f(relExp_norm)
3. When expression profile is loaded from gene-Expression-Db: relExp-Values are normalized once in PK-Sim; normalized values are then set as relExp.
4. When user changes relExp manually: nothing happens (no normalization etc.)
5. I would introduce a "Normalize relative Expressions" button in the relExp-Tab in the UI. If user clicks on it: relExp-Values are normalized

**Comment by Yuri05** [comment]
just tried optimization of relExp in PK-Sim. No idea what happens but I wouldn't trust the result.


1. Initial state
![grafik](https://user-images.githubusercontent.com/25061876/73353952-ca02de00-4294-11ea-8da3-eccde690f9e2.png)

2. Optimizing relExp_BloodCells(normalized). Optimal value is 4
![grafik](https://user-images.githubusercontent.com/25061876/73354127-367ddd00-4295-11ea-9812-f483de820eec.png)

3. After Transfer PI==>Simulation
![grafik](https://user-images.githubusercontent.com/25061876/73354172-5a412300-4295-11ea-9dc8-117bc0af03ce.png)

4. Commit to Individual. In individual I have now
![grafik](https://user-images.githubusercontent.com/25061876/73354338-c4f25e80-4295-11ea-90e7-d5194ae9471f.png)

5. in the simulation, set relExp Bone=1
![grafik](https://user-images.githubusercontent.com/25061876/73354572-5235b300-4296-11ea-8300-188fc45246bf.png)

**Comment by PavelBal** [comment]
> just tried optimization of relExp in PK-Sim. No idea what happens but I wouldn't trust the result.

lol, I think this is a good example why we should get rid of the automatic normalization :D

I like your proposal.

In total, we have the following parameters refering to the "relative expression":
- Relative expression **local**
- Relative expression (normalized) **local**
- Relative expression in plasma **global**
- Relative expression in plasma (normalized) **global**
- Relative expression in blood cells **global**
- Relative expression in blood cells (normalized) **global**
- Relative expression in vascular endothelium **global**
- Relative expression in vascular endothelium (normalized) **global**
- Relative expression out. **local**

The biggest "pain" are the local parameters, as there are tons of them.

Getting rid of normalized values would minimze the list to:

- Relative expression **local**
- Relative expression in plasma **global**
- Relative expression in blood cells **global**
- Relative expression in vascular endothelium **global**
- Relative expression out. **local**

Now we could also think about a way to generalize the "Relative expression out."? Especially for adding new proteins, it is always cumbersome to select the right formula (and sometimes the formula might not be present and must be created first).  @Yuri05 can you provide a list of all possible formulas used for "Relative expression out."?

**Comment by Yuri05** [comment]
<details><summary>all rel exp formulas</summary>

FORMULA_RATE | FORMULA
-- | --
RelExpBloodCellsGlobal | rel_exp_bc
RelExpBloodCellsNormGlobal | rel_exp_bc_norm
RelExpEndosomal | rel_exp_norm / f_endo
RelExpInterstialForInterstitial | f_cell/f_int * rel_exp_norm + V_vasend/V_int * rel_exp_vendo_norm
RelExpInterstialIntraVascEndoIsInterstitial | V_vasend/V_int * rel_exp_vendo_norm
RelExpInterstialMembraneExtracellularApical | f_cell/f_int * rel_exp_norm
RelExpInterstialMembraneExtracellularBasolateral | f_cell/f_int * rel_exp_norm+ V_vasend/V_int * rel_exp_vendo_norm
RelExpOutFromNorm | rel_exp_norm
RelExpPlasmaGlobal | rel_exp_pls
RelExpPlasmaMembraneExtracellularApicalBloodOrgan | rel_exp_norm + HCT / (1-HCT) * rel_exp_bc_norm
RelExpPlasmaMembraneExtracellularApicalTissueOrgan | rel_exp_norm + HCT / (1-HCT) * rel_exp_bc_norm + V_vasend/V_pls * rel_exp_vendo_norm
RelExpPlasmaMembraneExtracellularBasolateral | rel_exp_norm+ HCT / (1-HCT) * rel_exp_bc_norm
RelExpPlasmaNormGlobal | rel_exp_pls_norm
RelExpVascEndoGlobal | rel_exp_vendo
RelExpVascEndoNormGlobal | rel_exp_vendo_norm

</details>

**Comment by StephanSchaller** [comment]
> just tried optimization of relExp in PK-Sim. No idea what happens but I wouldn't trust the result.

Exactly, and I don't see a big benefit for the automated normalization.

In my opinion, it would be enough to have the relative expressions directly defined in % (of reference concentration) and they can take any value (0 to "inf" %).

Also, it has to be made a lot more transparent how the "localization" in tissue affects the effffective protein levels in the organ subcompartments.

**Comment by StephanSchaller** [comment]
Or we have to rethink the "localization" in tissue UI

**Comment by msevestre** [comment]
I think we need to involve PK-Sim users here if we decide to change one of the core concepts.

**Comment by StephanSchaller** [comment]
> I think we need to involve PK-Sim users here if we decide to change one of the core concepts.

Yes, but we have already some involved in the discussion ;-) (we are not only MoBi users)

**Comment by msevestre** [comment]
Sorry as far as I am concerned, you are not the typical PK-Sim users.

**Comment by PavelBal** [comment]
An attempt to solve

`2. Localization in XXX. Currently only part of PK-Sim logic. Should we try to bring it somehow to MoBi (especially if we are going to add proteins in MoBi as well)?`

There are two problems: 
1) It is not obvious how the different choices of the "localization" affect the expression in PK-Sim
2) It is very hard to understand how the different proteins are expressed in MoBi. It is even harder if introducing a protein with a localization different from the already present enzymes, because the localization is determined by the choice of the "rel exp out" formula.

I propose:
Instead of having one expression value per tissue, and selecting the localization, have up to three values:

-Intracellular RBC
- Membrane RBC
- Plasma
- VasEnd endosomal
- VasEnd apical
- VasEnd basolateral
- Tissue intracellular
- Tissue interstitial
- Tissue membrane

In the UI, these entries could be shown as sub-entries of the organs, which are not expanded by default. For convenience, the drop-down lists "Localization" can be left as is, and depending on the selected entry the expression values will be pre-filled. This would also give more flexibility, as it would be possible e.g. to define the expression of an enzyme intracellularly **and** on the membrane facing toward interstitial space.

The formula for "relative expression out" can be generalized, it would just sum up over the expression values of all relevant spaces.

The ultimate benefit for MoBi is that the expression is then determined solely by the values of the respective compartment, and not by the choice of the formula.

**Comment by msevestre** [comment]
I am not sure I understand. Instead of one global value for RBC, Plasma etc.. you would like to define this value for each compartment?...

**Comment by StephanSchaller** [comment]
> I am not sure I understand. Instead of one global value for RBC, Plasma etc.. you would like to define this value for each compartment?...

No I think its meant like this: 
For RBC define:
- Intracellular RBC
- Membrane RBC
For Plasma it is only Plasma
And for each Tissue Organ you can separately define (fractional?) expression for:
- VasEnd endosomal
- VasEnd apical
- VasEnd basolateral
- Tissue intracellular
- Tissue interstitial
- Tissue membrane

But there are some overlaps, that need to be handled as some of above selections effectively represent the same compartment (but maybe that's not a problem as you would then just sum up the defined levels).

I am not sure if the (required) logic of PK-Sim and MoBi are the same, here, as in MoBi you might need more flexibility which you don't need in PK-Sim but having the same (more complex) logic would probably reduce confusion if both tools are used.

> For convenience, the drop-down lists "Localization" can be left as is

But maybe with more felxibility

**Comment by Yuri05** [comment]
If I understand you correctly, Pavel, you suggest something like this:
1. All localization flags will be defined as properties per protein
2. Every compartment becomes all _potential_ relExp as parameters
3. relExpOut in a compartment would be **always** the sum of all potential relExps
4. every potential relExp is set either to zero or to some input relExp depending on the localization flags

E.g. in plasma:
```
relExpOut_Plasma = relExpPlasma + f1*relExpPlasma_BC + f2*relExpPlasma_VascEndo

relExpPlasma_BC = LocalizationTissue == MEMBRANE_EXTRACELLULAR ? relExpBC : 0
relExpPlasma_VascEndo = MEMBRANE_EXTRACELLULAR_APICAL ? relExp_VascEndo : 0

with  f1 = HCT / (1-HCT)  and f2 = V_vascend/V_pls
```

This would replace the current formulas in plasma below:

FORMULA_RATE | FORMULA
-- | --
RelExpPlasmaMembraneExtracellularApicalBloodOrgan | rel_exp_norm + HCT / (1-HCT) * rel_exp_bc_norm
RelExpPlasmaMembraneExtracellularApicalTissueOrgan | rel_exp_norm + HCT / (1-HCT) * rel_exp_bc_norm + V_vasend/V_pls * rel_exp_vendo_norm
RelExpPlasmaMembraneExtracellularBasolateral | rel_exp_norm+ HCT / (1-HCT) * rel_exp_bc_norm
RelExpPlasmaNormGlobal | rel_exp_pls_norm

**Comment by PavelBal** [comment]
> Every compartment becomes all potential relExp as parameters per protein

Yes, or - even more simplistic - every _organ_ becomes parameters r`el exp intracellular`, `rel exp interstitial`, `rel exp membrane`, and the three for the endolelium (do we really need three?) per protein.

> relExpOut in a compartment would be always the sum of all potential relExps

Yes. No need for different formulas.

> every potential relExp is set either to zero or to some input relExp

Yes.

Now, to "localization flags". I did not think of them at all, my suggestion was that the protein can be expressed everywhere. However, to not change too much at the beginning, we can stick to the localization and use the solution proposed by @Yuri05 
-All localization flags will be defined as (global) properties per protein
-every potential relExp is set either to zero or to some input relExp depending on the localization flags

I like it.

**Comment by Yuri05** [comment]
>Yes, or - even more simplistic - every organ becomes parameters rel exp intracellular, rel exp interstitial, rel exp membrane, and the three for the endolelium (do we really need three?) per protein.

Yep, even better.

**Comment by PavelBal** [comment]
I have made a list of the possible localizations of proteins and where they are represented in the model. We should discuss which of these cases we want to cover (probably all of them):

_in vivo_ | Model | Remarks
--|--|--
**Tissue** 
Intracellular | Intracellular
Interstitial | Interstitial
Cell membrane | Interstitial
Cell membrane apical | Lumen
**Vasculature**
Plasma | Plasma
RBC intracellular | RBC
RBC cell membrane | Plasma
Endothelial intracellular | Not available | Current: interstitial *
Endothelial endosome | Endosome
Endothelial cell membrane | Plasma | Facing plasma **
Endothelial cell membrane | Interstitial | Facing tissue ***

**Remarks:**
* I do not agree with the descision to place enzymes expressed in endothelium into the interstitium of the organs. However, as we do not have endothelial cellular space, I would not know where to put them. We mighth concider replacing "Endosome" with "Endothelial cells", er extend the model by "Endothelial cells":

** This is definitely common that enzymes are expressed on the cell surface os the endothelial cells facing towards plasma, we need it.

*** However I am not sure how common it is that an enzyme is present on the cell of the endothelial cell facing interstitial space of an organ. Maybe we do not need it.

**Comment by StephanSchaller** [comment]
Maybe we need to approach this from the other way…. what are the assays actually measuring that provide the values within the databases? And do we need to provide an input interface for such measurements? (Probably, yes). So we should collect examples / use-cases.
Other than that, we just need a way to (manually) set enzyme levels in the explicit compartments in the model (not caring where they are ACTUALLY located in vivo (Membrane X.Y,Z)), right?
