### ISSUE TITLE
Parameters defined by ODE: Parameter Values or Initial Conditions

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSMOSES#15]
I know that we discussed it again, but I cannot remember what was the solution:

Do parameters that are defined by an ODE belong to the list of Parameter Values or Initial Conditions?

It is more logical to list them under Parameter Values, as those are, well, parameters. The only problem is the scale factor - in theory it should be possible to change the scale factor for them, too. However, it was not possible until now, so it would be OK to let it out in the new version?

@Yuri05 @msevestre @StephanSchaller

**Comment by StephanSchaller** [comment]
> It is more logical to list them under Parameter Values

No, I disagree, for a modeller, if a parameter is defined as a state-variable, the "initial value" you then have to specify should also be listed as "initial condition".

We might need to aligning the nomenclature "initial value" / "initial condition"

**Comment by PavelBal** [comment]
In  this case: if an entry for molecule A in container B is not present in the list, then this molecule has status "not present" in this container. What about the parameter? How does this work together with the idea of only listing parameter whose values are changed?

**Comment by msevestre** [comment]
Didn't we say we didn't have IC anymore?
I think no one complained about scale factor for Parameter and it's safe to
assume than no one really missed it

**Comment by msevestre** [comment]
Or are we renaming MSV to IC?

**Comment by StephanSchaller** [comment]
I guess this is a technical issue. This simply means the "initial value" is no longer defined at the parameter (NaN, or there simply is no corresponding UI element), but in the "initial conditions" BB.

Also, the R-function "setSpeciesInitialValues" would need to handle parameters that are StateVariables. Again, we might need to change Nomenclature to be precise (e.g. call it "setInitialConditions")

**Comment by StephanSchaller** [comment]
> Or are we renaming MSV to IC?

Correct

**Comment by msevestre** [comment]
I disagree with the technical issue. Having parameter values potentially in
two places is highly confusing don't you think?

**Comment by StephanSchaller** [comment]
> Having parameter values potentially in two places is highly confusing don't you think?

Depends who you are asking, I guess (modeller vs lay person). 
These "parameters" are anyway of a special case... and technically are not (input) parameters at all... but state variables of the model (just like species)
So, are "Initial Values" then really Parameter Values? 
Because for a Parameter defined as State Variable, its (current) value is defined by the differential equation.

**Comment by Yuri05** [comment]
my vote: Parameter Values. 
Apart from arguments already given above, if we are going to keep the possibility to switch between "normal" parameter and "ODE"-parameter just via selecting/deselecting a checkbox: having ODE parameter initial value in IC would mean that it must be moved between PV and IC every time user activates/deactivates this option. Not impossible, but seems confusing from users perspective and also means some additional implementation effort.

**Comment by PavelBal** [comment]
I also vote for Parameter Values, especially with Yuris argument.

**Comment by StephanSchaller** [comment]
Technically, the (non-ODE) Parameter does not appear in the PV BB by default, but only if changed. Also, I don't think users would switch back and forth between "normal" and "ODE"...

… okay... if you all vote like this… but are the ICs of these "ODE" parameters handled with "setSpeciesInitialValue" at the moment?

**Comment by PavelBal** [comment]
> Also, I don't think users would switch back and forth between "normal" and "ODE"...

I am doing it often...

> but are the ICs of these "ODE" parameters handled with "setSpeciesInitialValue" at the moment?

At the moment? You mean, in the "old" r-toolbox?

**Comment by StephanSchaller** [comment]
> At the moment? You mean, in the "old" r-toolbox?

Jop

**Comment by PavelBal** [comment]
Remains as it is - start value of a state variable parameter is stored in the PV BB (if changed, otherwise in the source BB).
