### ISSUE TITLE
Vascular endothelium in non-tissue vascular organs

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSMOSES#19]
The blood organs 

- ArterialBlood
- PortalVein
- VenousBlood

do not have the sub-compartment `Endosome` and the parameter `Volume (endothelium)`. I think this is not correct and these organs should be extended by the endorhelium parameter/compartment.

**Comment by StephanSchaller** [comment]
I believe this was omitted as it would not contribute a lot given the smaller vascular surface area (on which endosomal volume depends on) in these blood organs (surface area of one big vein/artery << surface area of thousands of tiny vessels in the organs)
