### ISSUE TITLE
MoBi: PK-Sim module representation

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSMOSES#22]
A module with one entity of each Building Block 

Spatial Structure | Molecules | Reactions | Passive Transports | Observers | Events | PV | IC
-- | -- | -- | -- | -- | -- | -- | --

And a snapshot.

**Comment by PavelBal** [comment]
PK-Sim modules cannot be edited by default. If the user decides to edit a PK-Sim module, the PK-Sim module will be converted to an extension module. Every PK-Sim module will contain the snapshot of the PK-Sim model that will allow recreating of the model in PK-Sim. As one PK-Sim model can result in multiple PK-Sim modules in MoBi, the same snapshot can be assigned to multiple modules.

**Comment by msevestre** [comment]
Do we delete the snapshot if the user edits the PK-Sim Module and make it an extension module? It would be a mismatch

**Comment by PavelBal** [comment]
Yes.
