### ISSUE TITLE
MoBi: Parameter Values BB

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSMOSES#24]

**Comment by PavelBal** [comment]
Values of parameters (global and local). Only list parameters (including ODE-based) which values are different from the original value in the BB.

**Comment by msevestre** [comment]
What's ODE Based? PArmaeter with RHS?

**Comment by PavelBal** [comment]
Yes.

**Comment by StephanSchaller** [comment]
See discussion https://github.com/Open-Systems-Pharmacology/OSMOSES/issues/15

Technically, we need two entries for Parameters with RHS, one for the Initial Value and one for the RHS value?
