### ISSUE TITLE
MoBi: Initial Conditions BB

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSMOSES#25]
An n x m list, with n the number of (floating) molecules and m the number of containers, holding start values of molecules, the corresponding scaling factors, and the "negative values allowed" property. If an entry for molecule a in container b is not in the list, the molecule is "not present" in this container.

**Comment by StephanSchaller** [comment]
IC for parameters defined by ODE are not part of ICs as they would then appear/disappear if a parameter is switched between w/wo RHS. (but do we really switch?)
