### ISSUE TITLE
Create a new Container in the spatial structure (Building Block) of a module

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSMOSES#29]
In an empty SS-BB of a module, create a new top container. A container creation frame appears (e.g. similar to "new parameter"), where the user has to define the name, the type (logical or physical), `Parent container`, and default values for (as check-boxes resp. radio buttons):

-- | isPresent | Negative values allowed
--|--|--
Floating | Yes | No 
Enzyme| Yes | No 
Transporter | Yes | No 

The property `Parent container` can be entered manually as a path to the parent container, or selected from a tree view of the containers present in the PK-Sim module.

**Comment by PavelBal** [comment]
If the module contains molecules, the `IC` list is automatically extended by the entries of these molecules in the newly added container. Properties `isPresent` and `Negative values allowed` are set according to the selection of the default values made for the container. Initial values are set to 0 (if not defined by a formula in the molecule).

**Comment by msevestre** [comment]
What happens is there is no PKSim Module? 

What about multiple PKSim Module. Or do we allow only one per project?

**Comment by msevestre** [comment]
`ParentContainerPath` is optional correct? A container can be added as child to another existing container, right?

**Comment by PavelBal** [comment]
- Multiple PK-Sim modules are allowed
- If no PK-Sim module is present, no suggestions for `parent container` are shown.
- If multiple PK-Sim modules are present, multiple spatial structure Building Blocks are shown (as now when multiple spatial structures are present)
- `ParentContainerPath` is a mandatory property for each container. If a container is added as a child of an existing container, its `ParentContainerPath` is automatically set to the path of its parent container (this is a tricky one, maybe this parent container path must be constructed recursively from the parent container paths of the parent container)

`ParentContainerPath` is mandatory for each container so organs can be easily extracted e.g. from PK-Sim modules. E.g., "Save as pkml" in the kidney-container of a PK-Sim module will save the organ and set `ParentContainerPath` to "Organism".
