### ISSUE TITLE
Create a new molecule in a module

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSMOSES#30]
Creation of a new molecule in a module.

A property "Molecule type" cane be defined (one selection only):

- Floating
- Enzyme
- Transporter

In the `IC` list, entries of the newly created molecule for all containers in (all) PK-Sim modules and the module where the molecule is defined are created, based on the default values for "isPresent" and "negative values allowed" defined for the containers.

**Comment by msevestre** [comment]
How do we deal with other types of molecules ? Metabolite, Complex etc..

**Comment by StephanSchaller** [comment]
> How do we deal with other types of molecules ? Metabolite, Complex etc.

Technically, these are just "tags" but not types in a sense how they are structurally handled in the model.

**Comment by msevestre** [comment]
@StephanSchaller ??

When I have a complex, it is not an enzyme, and not a transporter. I don't want to set it to Floating. 
So what's the value of the molecule Type? I don't think this description is complete

**Comment by StephanSchaller** [comment]
On a technical level, we only need to distinguish between floating and stationary, right? everything else is then a "tag" (or sub-category) for either of these types.
But I agree, some more description is required, this was only an "initiation".

**Comment by PavelBal** [comment]
No I realize that this might not be necessary any more, as with the expression redesign we now have proteins always present in all containers. Lets discuss.
