### ISSUE TITLE
"Project" ribbon tab

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSMOSES#35]
- Default output intervals
- Project display units
- Default solver settings
- Chart templates (https://github.com/Open-Systems-Pharmacology/OSMOSES/issues/7)
- Default output selection
- ...

**Comment by PavelBal** [comment]
- Save current simulation output as project defaults.

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/106919438-24b8ec00-66d8-11eb-907c-702f32f05c4a.png)
