### ISSUE TITLE
Every module inlcudes exactly one BB of each type. Empty BBs are allowed.

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSMOSES#36]
WHY? why aren't we allowing at most one BB of each type?

**Comment by StephanSchaller** [comment]
Because a second BB should be a separate sub-module (at least this was the idea to keep it simple, but can discuss implications/use-cases for a second/alternative BBs per submodule)

**Comment by msevestre** [comment]
My point is why so we say exactly one. iMO it could be at most one. (E.g 0 or 1)

**Comment by StephanSchaller** [comment]
Yes, the idea was that "0" would be an empty BB.

But the title here should be more specific. Are we talking about MoBi extension Module (xModule; what I believe) or PK-Sim module?
Technically xModules could have more than 1 BB for (Events?,) Parameters, and Initial Conditions BB types?

**Comment by msevestre** [comment]
Just copy paste from the wiki for points that needs to be clarified
