### ISSUE TITLE
Multple PK-Sim modules are always extended to a common PK-Sim module. Selected extension module 1 extends/overwrites the common PK-Sim module

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSMOSES#37]
What happens if a PKsim module overwrites another PKSim Module? I don't understand why there is a difference between PKSim Module and submodule behavior (aside from order of operations that is)

**Comment by StephanSchaller** [comment]
Not sure what the issue is. PK-Sim modules just need to be kept separate for re-qualification

**Comment by msevestre** [comment]
Why do we make the difference between extend/overwrite vs extend for pksim module. This has nothing to do with snapshot or requalification as far as I can tell. I just don't recall the nuances here

**Comment by StephanSchaller** [comment]
Yes, I am not sure this is up to date. In principle this issue just says, PK.Sim modules are combined hierarchically?
