### ISSUE TITLE
Documentation: when is the individuals-BB applied?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSMOSES#60]
During model creation from modules, where does the individuals-BB stand in the hierarchy?

**Comment by PavelBal** [comment]
@msevestre @rwmcintosh could you help out, please?

**Comment by rwmcintosh** [comment]
Quantities are updated from these similar objects in this order

- InitialConditions
- Expressions
- Individual
- ParameterValues

**Comment by rwmcintosh** [comment]
collectively - this is the last stage in creating a model, updating the quantities from these paths.

**Comment by PavelBal** [comment]
The behavior seems to be inconsistent. For Expression Profiles, the values are treated as a  PV BB, so they are applied on top of any values defined in other building blocks:

-----------
The final values of the parameters are determined in the following order:

1. **Values defined in the Building block.**  First, the value that is defined in the BB where the parameter is defined. E.g., `CYP3A4|Reference concentration` is set to 1 µmol/l in the Molecules BB. If a simulation is created only with the module with this Molecules BB without selection of an Expression Profile or a PV BB, the value will be 1 µmol/l.
2. **Values defined in an Expression Profile.** If an expression profile is selected, the values from the expression profile are applied. E.g., `CYP3A4|Reference concentration` is set to 4.32 µmol/l in the Molecules BB. If a simulation is created with the module with the Molecules BB and the Expression Profile, the value will be 4.32 µmol/l.
3. **Values defined in the PV BBs.** If a module is selected that contains a PV BB, the values from the PV BB are applied. If multiple modules have PV BBs with entries for the same parameters, the value from the latest module is selected. E.g., if the Extension module has an entry for `CYP3A4|Reference concentration` with the value of 2 µmol/l, and a simulation is created with the module with the Molecules BB where the value is 1 µmol/l, the Expression Profile where the value is 4.32 µmol/l, and the PV BB where the value is 2 µmol/l, the value in the simulation will be 2 µmol/l.
--------------

This is different for the individual BB:
If there is an extension module with the parameter `Volume` defined for `Organism|ArterialBlood` in the spatial structure of the Extension module, the value will be applied disregarding what value is defined in the Individual BB.

I think this must be changed. @msevestre @Yuri05 We should discuss this.

**Comment by msevestre** [comment]
Hum. Individual values are applied last, AFTER we merge the extension modules.

**Comment by PavelBal** [comment]
But somehow they do not update the values.

**Comment by msevestre** [comment]
ok can you show me a `simple` project where I can reproduce

**Comment by PavelBal** [comment]
[individual-profile-overwritten_simplified.zip](https://github.com/user-attachments/files/16472585/individual-profile-overwritten_simplified.zip)

`simple` still needs to be a full PBPK, I guess.

In this project, a PK-Sim module `iv 0.05 mg/kg (2 min)` is combined with the Extension module `AB` and an Individual BB. `AB` has the merge behavior "Extend" and contains the container `Organism|ArterialBlood` with the parameter `Volume = 0.5l`. In the Individual, the volume is 0.42l. When combining the modules, the value in the simulation is 0.5l.

**Comment by PavelBal** [comment]
Must have been fixed by now.
